# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title               : Fuss und Radentscheid Dresden
email               : kontakt@furedd.de
description         : >- # this means to ignore newlines until "baseurl:"
  Der Entscheid für eine klimagerechte, verkehrssichere Stadt mit hoher Lebensqualität.
  Für ein lebenswertes, kinderfreundliches und klimagerechtes Dresden braucht es eine bessere Infrastruktur
  für Radfahrende und Fußgänger:innen. Der für eine zukunftsfähige Stadt notwendige Ausbau und die Verbesserungen
  erfolgen aktuell viel zu langsam und zu wenig. Nach dem Vorbild von über 40 deutschen Radentscheiden planen
  wir deshalb einen Bürgerentscheid, um die Stadt Dresden jetzt zum ganzheitlichen Handeln aufzufordern!
url                 : "https://robtranquillo.github.io" # The base hostname & protocol for your site, e.g. http://example.com
baseurl             : "/fuss-und-radentscheid-dresden" # The subpath of your site, e.g. '/blog' (does not include the hostname).
header-display-title: false

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/FuRe_DD?ref_src=twsrc%5Etfw"


# Build settings
repository: "RobTranquillo/fuss-und-radentscheid-dresden"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: _fussradentscheid
logo: assets/images/logo.png
plugins:
  - jekyll-feed
github: [metadata]

# Theme settings
locale: de     #translations are at: _data/ui-text.yml

# Where things are
source              : .
destination         : ./_site
# collections_dir     : cards # Only uncomment, if differs from '.' (Hardcoded default: '.').
plugins_dir         : _plugins # Takes an array of strings and loads plugins in that order.
layouts_dir         : _layouts
data_dir            : _data # See: https://jekyllrb.com/docs/datafiles
includes_dir        : _includes

# Sass configuration
sass:
  style             : expanded # The style of the CSS-output (Possible values: 'expanded', 'nested', 'compact', or 'compressed').
  sass_dir          : _sass # A filesystem-path which should be searched for Sass partials.
  load_paths        : [] # An array of additional filesystem-paths which should be searched for Sass partials.
  line_comments     : true # Include the line number and filename of the source in the compiled CSS-file.
  sourcemap         : always # Controls when source maps shall be generated (Possible values: 'never', 'always' or 'development').

# Handling Reading
safe                : false # Disable non-whitelisted plugins, caching to disk, and ignore symbolic links.
disable_disk_cache  : false
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : true # Cause a build to fail if there is a YAML syntax error in a page's front matter.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - .gitignore
  - .gitattributes
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Filtering Content
show_drafts         : true # Process and render draft posts.
limit_posts         : 0 # Limit the number of posts to parse and publish.
future              : true # Publish posts or collection documents with a future date.
unpublished         : false # Render posts that were marked as unpublished.

# Collections
collections:
  posts:
    output          : true # Render posts in general, not changeable because hardcoded in Jekyll.
  none:
  cards:
  # home:

# Plugin settings
whitelist           : []
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
# - jekyll-github-metadata # Required for GitHub metadata (see: https://jekyll.github.io/github-metadata/site.github)
# - jekyll-gist # Required for GitHub Gist support
# - classifier-reborn # Required for LSI
# - jekyll-paginate # Required for pagination
# - jekyll-feed
# - jekyll-sitemap

# Conversion settings
markdown            : kramdown
highlighter         : rouge
lsi                 : false # Produce an index for related posts.
excerpt_separator   : "\n\n"
incremental         : false # Incremental build only re-builds posts and pages that have changed, but may also break site generation in certain cases.

# Markdown Processors
kramdown:
  hard_wrap         : false # Insert HTML <br /> tags inside paragraphs where the original Markdown document had newlines.
  gfm_quirks        : [] # Enables a set of GFM specific quirks (Possible values: 'paragraph_end' and/or 'no_auto_typographic').
  auto_ids          : true # Use automatic header ID generation
  entity_output     : as_char # Defines how entities are output
  toc_levels        : [1, 2, 3, 4, 5, 6] # Defines the levels that are used for the table of contents
  smart_quotes      : lsquo,rsquo,ldquo,rdquo # Defines the HTML entitiy names or code points for smart quote output
  input             : GFM # GitHub Flavored Markdown (see: https://github.github.com/gfm)
  footnote_nr       : 1 # Number of the first footnote
  show_warnings     : true
  math_engine       : mathjax
  syntax_highlighter: rouge

# Serving settings
detach              : false # Detach the server from the terminal.
port                : 4000 # Listen on the given port. The default is `4000`.
host                : 127.0.0.1 # Listen at the given hostname. The default is `localhost`.
show_dir_listing    : false # Show a directory listing instead of loading your index file.
# open_url            : true # Open the site's URL in the browser.
force_polling       : false # Forces liquid during watching to use the polling architecture rather than inotify.
livereload          : true # Reload a page automatically on the browser when its content is edited.
livereload_ignore   : [] # File glob patterns for LiveReload to ignore.
livereload_min_delay: 5 # Minimum delay before automatically reloading page.
livereload_max_delay: 10 # Maximum delay before automatically reloading page.
skip_initial_build  : false # Skips the initial site build which occurs before the server is started.
profile             : true # Generate a Liquid rendering profile to help you identify performance bottlenecks.

# Output settings
quiet               : false # Silence the normal output from Jekyll during a build.
verbose             : true # Print verbose output.
timezone            : Europe/Berlin
# paginate            : 5 # How many items should be displayed per page.
# paginate_path       : /blog/page:num/
# permalink           : /:basename:output_ext

# Liquid settings
# liquid:
#   error_mode        : strict # Response to errors (Possible values: 'lax', 'warn' or 'strict').
#   strict_filters    : true # Catch non-existing filters.
#   strict_variables  : true # Catch non-assigned variables.
